const Router = require('koa-router')
const router = new Router()
const room_controller = require('../../app/controllers/room_controller')

router.post('/addRoomKind', room_controller.addRoomKind)
router.post('/getRoomKind', room_controller.getRoomKind)
router.post('/getKindImg', room_controller.getKindImg)
router.post('/updatedRoomKind', room_controller.updatedRoomKind)
router.post('/addRoom', room_controller.addRoom)
router.post('/getRoomList', room_controller.getRoomList)
router.post('/delRoom', room_controller.delRoom)
router.post('/updatedRoom', room_controller.updatedRoom)
router.post('/searchRoom', room_controller.searchRoom)
router.post('/getKindRoom', room_controller.getKindRoom)
router.post('/getOrderRoom', room_controller.getOrderRoom)
router.post('/searchOrderRoom', room_controller.searchOrderRoom)
router.post('/orderRoom', room_controller.orderRoom)
router.post('/getRoomInfo', room_controller.getRoomInfo)
router.post('/bookRoomInfo', room_controller.bookRoomInfo)
router.post('/getBookList', room_controller.getBookList)
router.post('/cancelBook', room_controller.cancelBook)
router.post('/getBookInfo', room_controller.getBookInfo)
router.post('/updatedBookInfo', room_controller.updatedBookInfo)
router.post('/getOrderList', room_controller.getOrderList)
router.post('/searchOrderList', room_controller.searchOrderList)
router.post('/getCheckOutInfo', room_controller.getCheckOutInfo)
router.post('/getCheckOutList', room_controller.getCheckOutList)
router.post('/cancelCheckOut', room_controller.cancelCheckOut)
router.post('/updateCheckInfo', room_controller.updateCheckInfo)
router.post('/checkedOut', room_controller.checkedOut)
router.post('/adjustBook', room_controller.adjustBook)
router.post('/adjustCheckedOut', room_controller.adjustCheckedOut)
router.post('/getHistoricalList', room_controller.getHistoricalList)
router.post('/searchHistoryList', room_controller.searchHistoryList)

module.exports = router